### ISSUE TITLE
Proposal: make structs opaque by default

### ISSUE THREAD

**Issue by nikomatsakis** [tschneidereit/typed-objects-explainer#2]
Opaque types will be easier to optimize and less error prone. They are easier to optimize because they given strong aliasing guarantees. They are less error prone because you cannot wind up "reinterpret casting" a buffer in crazy ways. I also believe that the most common use of typed objects will be to give more structure to existing JS classes and types and to gain efficiency: for this purpose, transparency is not needed. Therefore, we should make opaque the default. 

To achieve this, we can add an optional argument to struct type containing options. One such option can be `transparent`:

```
var PointType = new StructType({x, y}, {transparent: true});
```

**Comment by erights** [comment]
Opaque by default fits with good software engineering and security best practices. I am strongly enthusiastic about this proposal.

**Comment by dschenkelman** [comment]
I was just reading the spec (it was really easy to understand) and this is the first thing that came to mind. +1 for opaque structs. 

I assume the same `{ transparent: true }` would need to be added to the `arrayType` method?
